### ISSUE TITLE
Incompatible with Python 3.4

### ISSUE THREAD

**Issue by david-jarman** [uvd/PyRow#1]
Current working version does not run under Python 3.4. Main issue is that the print statements are in the Python 2 syntax (print "hello") which results in errors when porting the code to Python3.X versions.

**Comment by kylegoetz** [comment]
I'm actually rearranging this code to be a module that could be built and installed using pip. Not there yet, but I'm making it py3 compatible.

**Comment by david-jarman** [comment]
I had forgotten all about this. Glad the project isn't totally dead.

**Comment by MoralCode** [comment]
https://github.com/droogmic/Py3Row may be related and/or useful to upstream
